---
title: |
  | Introduction to R for Disease Surveillance 
  | and Outbreak Forecasting
subtitle: |
  | A workshop developed by the EPIDEMIA project 
  | with support from the US National Institutes of Health
  | Organized by the Health, Development, and Anti-Malaria Association in collaboration with the University of Oklahoma and the Amhara National State Regional Health Bureau
date: October 22 -- 26 2018, Bahir Dar, Ethiopia
author: |
  | Presented by Dr. Michael Wimberly, Dr. Dawn Nekorchuk, Andrea Hess
  | Department of Geography & Environmental Sustainability, University of Oklahoma

output:
  pdf_document: default
  html_document: default
---

\pagenumbering{gobble}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

This workshop will provide an introduction to statistical computing using the R computer language and software environment. R is open-source software that is available to users at no cost and runs on a wide variety of computer systems. As a result, R has become one of the most popular statistical software packages with an expanding community of users worldwide. These users have developed thousands of add-on “packages” that provide access to cutting-edge methods for data manipulation, statistical analysis, and graphics. This vast library of available tools, combined with the accessibility, flexibility, and extensibility of R, make this software ideal for developing informatics applications to support public health surveillance.

The challenge of using R lies in the need for users to write computer code rather than navigate a menu-based graphical user interface. Learning R therefore requires an investment of time and energy. The purpose of this workshop is to provide participants with focused instruction to help them get over the initial learning curve. Participants who complete the workshop will learn to write R scripts that will allow them to import datasets, manipulate and reformat the data, carry out some basic statistical analyses, and generate basic visualizations. 

The skills learned in the beginning of the workshop will provide the foundation for the training focused on malaria surveillance and forecasting reports later in the week, using the `epidemiar` R package created by the EPIDEMIA team.



